### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by zeroasterisk** [NirDiamant/RAG_Techniques#10]
What do you think about a leaderboard across these implementations, using the same datasets (Nvidia ChatQA or ServiceNow Repliqa)?

I know of the hallucination leaderboard on huggingface, but I don't know of a RAG pattern leaderboard yet. 

This repo and similar articles help the community share a taxonomy, but a leaderboard would help us compare.

**Comment by NirDiamant** [comment]
I agree with a slight reservation: Since the different methods often complement rather than contradict each other, I’m not sure if direct comparison makes the most sense. However, I agree with the importance of comparing different versions of your RAG system (which might combine several methods) against a given benchmark. Such comparisons should also account for dynamic changes in hyper-parameters, as an arbitrary configuration might not accurately reflect the value of a particular method or RAG system.

This idea is totally on the table right now :)

I encourage you to start this conversation on the Discord server. I believe interesting insights and potential contributions will emerge there.
